"""
DOCUMENTATION WRITER - Automatic Documentation Generator
=========================================================
Generates comprehensive documentation for applications.

Includes: README, API docs, deployment guides, user guides

Created: 2025-11-22
Trinity Build: Phase 2
"""

from datetime import datetime
from typing import Dict, Any, List
from dataclasses import dataclass

@dataclass
class Documentation:
    """Generated documentation"""
    readme: str
    api_docs: str
    deployment_guide: str
    user_guide: str
    changelog: str

class DocumentationWriter:
    """
    Generates comprehensive documentation.
    """

    def __init__(self):
        self.generation_count = 0

    def generate_readme(self, spec: Dict[str, Any]) -> str:
        """Generate README.md content."""
        app_name = spec.get("name", "app")
        description = spec.get("description", "An application")
        features = spec.get("features", [])
        tech_stack = spec.get("tech_stack", {})

        features_md = "\n".join(f"- {f.replace('_', ' ').title()}" for f in features)
        tech_md = "\n".join(f"- **{k}**: {v}" for k, v in tech_stack.items())

        return f'''# {app_name.replace("_", " ").title()}

{description}

## Features

{features_md}

## Tech Stack

{tech_md}

## Quick Start

### Prerequisites

- Python 3.8+
- Node.js 16+ (for frontend)
- pip

### Installation

1. Clone the repository:
```bash
git clone https://github.com/your-username/{app_name}.git
cd {app_name}
```

2. Install dependencies:
```bash
pip install -r requirements.txt
```

3. Run the application:
```bash
python app.py
```

4. Open http://localhost:5000 in your browser

## API Documentation

See [API_DOCS.md](./docs/API_DOCS.md) for detailed API documentation.

## Deployment

See [DEPLOYMENT.md](./docs/DEPLOYMENT.md) for deployment instructions.

## Contributing

1. Fork the repository
2. Create your feature branch (`git checkout -b feature/AmazingFeature`)
3. Commit your changes (`git commit -m 'Add AmazingFeature'`)
4. Push to the branch (`git push origin feature/AmazingFeature`)
5. Open a Pull Request

## License

This project is licensed under the MIT License.

---

Generated by AI App Generator - Pattern Theory validated
'''

    def generate_api_docs(self, spec: Dict[str, Any]) -> str:
        """Generate API documentation."""
        app_name = spec.get("name", "app")
        features = spec.get("features", [])

        endpoints = []

        # Health endpoint
        endpoints.append('''### Health Check

```
GET /health
```

**Response:**
```json
{
  "status": "healthy"
}
```
''')

        # Feature-specific endpoints
        if "user_authentication" in features:
            endpoints.append('''### Authentication

#### Login

```
POST /api/auth/login
```

**Request Body:**
```json
{
  "email": "user@example.com",
  "password": "password123"
}
```

**Response:**
```json
{
  "token": "jwt_token_here",
  "user": {
    "id": 1,
    "email": "user@example.com"
  }
}
```

#### Register

```
POST /api/auth/register
```

**Request Body:**
```json
{
  "email": "newuser@example.com",
  "password": "password123"
}
```

**Response:**
```json
{
  "message": "User created successfully",
  "user": {
    "id": 2,
    "email": "newuser@example.com"
  }
}
```
''')

        if "database" in features:
            endpoints.append('''### Data Operations

#### Get All Items

```
GET /api/data
```

**Response:**
```json
{
  "items": [
    {"id": 1, "name": "Item 1", "value": 100}
  ],
  "total": 1
}
```

#### Create Item

```
POST /api/data
```

**Request Body:**
```json
{
  "name": "New Item",
  "value": 200
}
```

**Response:**
```json
{
  "id": 2,
  "name": "New Item",
  "value": 200
}
```
''')

        return f'''# API Documentation - {app_name.replace("_", " ").title()}

## Base URL

```
http://localhost:5000
```

## Authentication

Most endpoints require a JWT token in the Authorization header:

```
Authorization: Bearer <token>
```

## Endpoints

{"".join(endpoints)}

## Error Responses

All errors follow this format:

```json
{{
  "error": "Error message",
  "code": 400
}}
```

### Common Error Codes

- `400` - Bad Request
- `401` - Unauthorized
- `404` - Not Found
- `500` - Internal Server Error

---

Generated by AI App Generator
'''

    def generate_deployment_guide(self, spec: Dict[str, Any]) -> str:
        """Generate deployment guide."""
        app_name = spec.get("name", "app")

        return f'''# Deployment Guide - {app_name.replace("_", " ").title()}

## Railway (Recommended)

1. Install Railway CLI:
```bash
npm install -g @railway/cli
```

2. Login to Railway:
```bash
railway login
```

3. Initialize project:
```bash
railway init --name {app_name}
```

4. Deploy:
```bash
railway up
```

5. Get your URL:
```bash
railway domain
```

## Netlify (Frontend)

1. Build the frontend:
```bash
npm run build
```

2. Deploy to Netlify:
```bash
netlify deploy --prod
```

## Docker

1. Build the image:
```bash
docker build -t {app_name} .
```

2. Run the container:
```bash
docker run -p 5000:5000 {app_name}
```

3. Or use Docker Compose:
```bash
docker-compose up -d
```

## Environment Variables

Set these environment variables in your deployment:

| Variable | Description | Required |
|----------|-------------|----------|
| `FLASK_ENV` | Environment mode | Yes |
| `DATABASE_URL` | Database connection | Yes |
| `JWT_SECRET` | JWT signing secret | Yes |
| `PORT` | Application port | No |

## Monitoring

After deployment, set up monitoring:

1. Health check endpoint: `/health`
2. Recommended interval: 30 seconds
3. Alert on 3 consecutive failures

---

Generated by AI App Generator
'''

    def generate_user_guide(self, spec: Dict[str, Any]) -> str:
        """Generate user guide."""
        app_name = spec.get("name", "app")
        features = spec.get("features", [])

        sections = []

        if "user_authentication" in features:
            sections.append('''## Account Management

### Creating an Account

1. Click "Register" on the homepage
2. Enter your email and password
3. Click "Create Account"
4. Check your email for verification

### Logging In

1. Click "Login" on the homepage
2. Enter your credentials
3. Click "Sign In"
''')

        if "database" in features:
            sections.append('''## Managing Data

### Creating Items

1. Navigate to the Dashboard
2. Click "Add New"
3. Fill in the required fields
4. Click "Save"

### Editing Items

1. Click the item you want to edit
2. Modify the fields
3. Click "Update"

### Deleting Items

1. Select the item
2. Click "Delete"
3. Confirm the deletion
''')

        return f'''# User Guide - {app_name.replace("_", " ").title()}

## Getting Started

Welcome to {app_name.replace("_", " ").title()}! This guide will help you get started.

{"".join(sections)}

## Troubleshooting

### Common Issues

**Can't log in?**
- Check your email and password
- Try resetting your password
- Clear your browser cache

**Data not loading?**
- Refresh the page
- Check your internet connection
- Contact support

## Getting Help

- Email: support@{app_name.replace("_", "")}.com
- Documentation: /docs
- FAQ: /faq

---

Generated by AI App Generator
'''

    def generate_changelog(self, spec: Dict[str, Any]) -> str:
        """Generate changelog."""
        app_name = spec.get("name", "app")
        today = datetime.now().strftime("%Y-%m-%d")

        return f'''# Changelog - {app_name.replace("_", " ").title()}

All notable changes to this project will be documented in this file.

## [1.0.0] - {today}

### Added
- Initial release
- Core application structure
- User authentication (if enabled)
- Database integration (if enabled)
- REST API endpoints
- Comprehensive test suite
- Deployment configurations

### Security
- Input validation
- XSS protection
- CSRF protection
- JWT authentication

---

Generated by AI App Generator
'''

    def generate_all(self, spec: Dict[str, Any]) -> Documentation:
        """
        Generate all documentation.

        Args:
            spec: App specification

        Returns:
            Documentation with all documents
        """
        self.generation_count += 1

        return Documentation(
            readme=self.generate_readme(spec),
            api_docs=self.generate_api_docs(spec),
            deployment_guide=self.generate_deployment_guide(spec),
            user_guide=self.generate_user_guide(spec),
            changelog=self.generate_changelog(spec)
        )

    def to_dict(self, docs: Documentation) -> Dict[str, Any]:
        """Convert documentation to dictionary."""
        return {
            "readme_lines": docs.readme.count("\n"),
            "api_docs_lines": docs.api_docs.count("\n"),
            "deployment_lines": docs.deployment_guide.count("\n"),
            "user_guide_lines": docs.user_guide.count("\n"),
            "changelog_lines": docs.changelog.count("\n"),
            "total_lines": sum([
                docs.readme.count("\n"),
                docs.api_docs.count("\n"),
                docs.deployment_guide.count("\n"),
                docs.user_guide.count("\n"),
                docs.changelog.count("\n")
            ])
        }


# Testing
if __name__ == "__main__":
    writer = DocumentationWriter()

    print("=" * 60)
    print("DOCUMENTATION WRITER - TEST")
    print("=" * 60)

    spec = {
        "name": "test_app",
        "description": "A test application for demonstration",
        "features": ["user_authentication", "database", "rest_api"],
        "tech_stack": {
            "frontend": "React",
            "backend": "Flask",
            "database": "SQLite"
        }
    }

    docs = writer.generate_all(spec)
    summary = writer.to_dict(docs)

    print(f"\nDocumentation generated:")
    print(f"  README: {summary['readme_lines']} lines")
    print(f"  API Docs: {summary['api_docs_lines']} lines")
    print(f"  Deployment Guide: {summary['deployment_lines']} lines")
    print(f"  User Guide: {summary['user_guide_lines']} lines")
    print(f"  Changelog: {summary['changelog_lines']} lines")
    print(f"\nTotal: {summary['total_lines']} lines")

    print("\n" + "=" * 60)
    print("DOCUMENTATION WRITER OPERATIONAL")
    print("=" * 60)
